#' Create prediction model
#'
#' @param target_test_df A dataframe with columns relevant to the regression model, i.e., target variable and predictors
#' @param model_fit A "workflow" class object generated by the `create_fit` function
#'
#' @return A dataframe with predicted values appended to target_test_df
#' @export
#'
#' @include 05_create-fit.R
#'
#' @examples
#' train_df <- target_df(mtcars[1:16, ], 'gear', c("am", "vs"))
#' test_df <- target_df(mtcars[17:32, ], 'gear', c("am", "vs"))
#' x_recipe <- create_recipe(train_df, target_variable="gear")
#' x_spec_list <- create_spec_kmin(train_df, model_recipe=x_recipe, method="lm", target_variable="gear")
#' x_spec <- get_list_item(x_spec_list, n=1)
#' x_fit <- create_fit(x_recipe, x_spec, train_df)
#' create_model_prediction(test_df, x_fit )
#'
#' @import dplyr
#' @importFrom stats predict
#'
create_model_prediction <- function(target_test_df, model_fit) {

  if (!(inherits(target_test_df, "data.frame"))){
    stop("target_test_df must be a dataframe!")
  }

  if (!(inherits(model_fit, "workflow"))){
    stop("model fit must be of workflow class!")
  }

  prediction_model <- model_fit %>%
    stats::predict(new_data = target_test_df) %>%
    dplyr::bind_cols(target_test_df, .)
  #print("Prediction model produced!")
  return (prediction_model)
}
